// <auto-generated />
namespace utilidades.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Campos_Sistema_Y_Privado_En_Articulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campos_Sistema_Y_Privado_En_Articulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031800323_Campos_Sistema_Y_Privado_En_Articulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
